spring:
  profiles:
    active: local

---
spring:
  profiles: local

  datasource:
    platform: h2
    url: jdbc:h2:file:~/h2/venue_test;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: ming
    password: ming1
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

# jasypt encryptor
#jasypt.encryptor.bean=jasyptStringEncrpto

---

kakao:
  address:
    url: https://dapi.kakao.com
  appKey: KakaoAK 28cba50459be19a904d64abcf06292b9

